export const navigation = [
  { name: 'Home', href: '/' },
  { name: 'Services', href: '/services' },
  { name: 'About', href: '/about' },
  { name: 'Gallery', href: '/gallery' },
  { name: 'Contact', href: '/contact' },
];

export const services = [
  {
    id: 'event-design-styling',
    title: 'Event Design & Styling',
    description: 'Thoughtfully curated event aesthetics including concept development, tablescapes, stage styling, luxury linens, focal points, and personalized design consultations tailored to your vision.',
    details: [
      'Concept development and mood boarding',
      'Tablescape and focal point design',
      'Stage styling and luxury linens',
      'Personalized design consultations',
    ],
  },
  {
    id: 'weddings-celebrations',
    title: 'Weddings & Celebrations',
    description: 'Elegant decor for weddings, milestone birthdays, bridal and baby showers, anniversaries, graduations, intimate gatherings, and other meaningful celebrations.',
    details: [
      'Wedding ceremony and reception design',
      'Milestone birthday styling',
      'Bridal and baby shower decor',
      'Anniversaries, graduations, and intimate gatherings',
    ],
  },
  {
    id: 'corporate-special-events',
    title: 'Corporate & Special Events',
    description: 'Stylish and impactful event environments for conferences, galas, corporate dinners, product launches, church events, networking events, fundraisers, and cultural celebrations.',
    details: [
      'Conferences, galas, and corporate dinners',
      'Product launches and networking events',
      'Church events and fundraisers',
      'Cultural celebrations',
    ],
  },
  {
    id: 'custom-installations-backdrops',
    title: 'Custom Installations & Backdrops',
    description: 'Statement installations designed to transform spaces, including luxury backdrops, floral walls, balloon styling, stage designs, signage, ceiling treatments, dance floor wraps, and entrance features.',
    details: [
      'Luxury backdrops and floral walls',
      'Balloon styling and stage designs',
      'Ceiling treatments and dance floor wraps',
      'Signage and entrance features',
    ],
  },
  {
    id: 'floral-design',
    title: 'Floral Design',
    description: 'Fresh and faux floral styling featuring centerpieces, arches, floral runners, hanging installations, ceremony florals, and elegant floral accents that elevate your event aesthetic.',
    details: [
      'Centerpieces, arches, and floral runners',
      'Hanging floral installations',
      'Ceremony florals',
      'Elegant floral accents',
    ],
  },
];

export const testimonials = [
  {
    id: 1,
    name: "Client",
    event: "Wedding",
    quote: "Nikie was our go-to for our wedding décor after seeing her work at a friend’s 40th birthday. She captured our vision perfectly and even coordinated with our florist and venue to ensure everything ran smoothly. Nikie was simply amazing—we would gladly work with her again.",
    image: "/testimonial-1.jpg",
  },
  {
    id: 2,
    name: "Client",
    event: "Wedding",
    quote: "If we were to do it again, we wouldn’t change a single detail from our wedding. Nikie didn’t just plan our event—she exceeded every expectation. Her creativity and dedication were simply outstanding.",
    image: "/testimonial-2.jpg",
  },
  {
    id: 3,
    name: "Client",
    event: "Wedding",
    quote: "I’m usually not one to give recommendations, but when it comes to wedding planning and décor—Nikie is the person to talk to. Just saying!",
    image: "/testimonial-3.jpg",
  },
  {
    id: 4,
    name: "Client",
    event: "Wedding",
    quote: "Nikie, the brain behind mmmdecors, is truly amazing to work with. Her style, creativity, and understated elegance made our wedding feel unique and memorable. We are so pleased with how beautiful our day turned out.",
    image: "/testimonial-4.jpg",
  },
  {
    id: 5,
    name: "Client",
    event: "Event",
    quote: "Her ability to remain positive, forward-thinking, and go the extra mile really stood out. For anyone looking for that special touch, mmmdecors is definitely the way to go!",
    image: "/testimonial-1.jpg",
  },
  {
    id: 6,
    name: "Client",
    event: "Wedding",
    quote: "Amazing is the word I would use for Nikie. We received so many compliments about the simplicity and elegance of our décor. Thank you, Nikie, for such an incredible job!",
    image: "/testimonial-2.jpg",
  },
  {
    id: 7,
    name: "Professional Partner",
    event: "Event Planning",
    quote: "Nikie doesn’t just execute a brief; she elevates it. Whether it’s translating a client’s vision or working through design challenges, she demonstrates creativity and professionalism. Highly recommended.",
    image: "/testimonial-3.jpg",
  },
  {
    id: 8,
    name: "Client",
    event: "50th Milestone Birthday",
    quote: "I’m still in awe of the beautiful decoration you created for my 50th milestone birthday Nikie. You turned the space into something so warm, vibrant, and unforgettable. You didn’t just decorate a venue, you rather created lasting memories.",
    image: "/testimonial-4.jpg",
  },
];

export const portfolioEvents = [
  {
    id: 1,
    title: 'Gold & Champagne Elegance',
    category: 'Wedding',
    image: '/portfolio/wedding-1.jpg',
    description: 'Luxurious wedding reception with dramatic florals and refined tablescape.',
  },
  {
    id: 2,
    title: 'Corporate Excellence Gala',
    category: 'Corporate',
    image: '/portfolio/corporate-1.jpg',
    description: 'Professional gala with minimalist sophistication and modern elegance.',
  },
  {
    id: 3,
    title: 'Milestone Celebration',
    category: 'Celebration',
    image: '/portfolio/celebration-1.jpg',
    description: 'Refined celebration with luxurious styling and premium details.',
  },
  {
    id: 4,
    title: 'Ceremony Perfection',
    category: 'Wedding',
    image: '/portfolio/wedding-2.jpg',
    description: 'Stunning ceremony backdrop with architectural florals and ambient lighting.',
  },
  {
    id: 5,
    title: 'Corporate Elegance Gala',
    category: 'Corporate',
    image: '/portfolio/corporate-2.jpg',
    description: 'High-end corporate event with sleek design and sophisticated atmosphere.',
  },
  {
    id: 6,
    title: 'Birthday Celebration',
    category: 'Celebration',
    image: '/portfolio/celebration-2.jpg',
    description: 'Elegant milestone celebration with refined decor and ambient warmth.',
  },
];

export const portfolioCategories = [
  { id: 'all', label: 'All Events' },
  { id: 'Wedding', label: 'Weddings' },
  { id: 'Corporate', label: 'Corporate' },
  { id: 'Celebration', label: 'Celebrations' },
];

export type GalleryCategory = 'Weddings' | 'Birthdays & Milestones' | 'Corporate';

export const galleryCategories: { id: GalleryCategory | 'All'; label: string }[] = [
  { id: 'All', label: 'All' },
  { id: 'Weddings', label: 'Weddings' },
  { id: 'Birthdays & Milestones', label: 'Birthdays & Milestones' },
  { id: 'Corporate', label: 'Corporate' },
];

export interface GalleryImage {
  src: string;
  category: GalleryCategory;
}

export const galleryImages: GalleryImage[] = [
  // New Weddings
  { src: "/WhatsApp Image 2026-06-01 at 6.58.23 PM.jpeg", category: 'Weddings' },
  { src: "/image.png", category: 'Weddings' },
  { src: "/image copy.png", category: 'Weddings' },
  { src: "/image copy 2.png", category: 'Weddings' },
  { src: "/image copy 3.png", category: 'Weddings' },
  { src: "/image copy 4.png", category: 'Weddings' },
  { src: "/image copy 5.png", category: 'Weddings' },
  { src: "/image copy 6.png", category: 'Weddings' },
  { src: "/image copy 7.png", category: 'Weddings' },
  { src: "/image copy 8.png", category: 'Weddings' },
  { src: "/image copy 9.png", category: 'Weddings' },
  { src: "/image copy 10.png", category: 'Weddings' },
  { src: "/image copy 11.png", category: 'Weddings' },
  { src: "/image copy 12.png", category: 'Weddings' },
  { src: "/image copy 13.png", category: 'Weddings' },
  { src: "/image copy 14.png", category: 'Weddings' },
  { src: "/image copy 15.png", category: 'Weddings' },
  { src: "/image copy 16.png", category: 'Weddings' },
  { src: "/image copy 17.png", category: 'Weddings' },
  { src: "/image copy 18.png", category: 'Weddings' },
  { src: "/image copy 19.png", category: 'Weddings' },
  { src: "/image copy 20.png", category: 'Weddings' },
  { src: "/image copy 21.png", category: 'Weddings' },
  { src: "/image copy 22.png", category: 'Weddings' },
  { src: "/image copy 23.png", category: 'Weddings' },
  { src: "/image copy 24.png", category: 'Weddings' },
  { src: "/image copy 25.png", category: 'Weddings' },
  { src: "/image copy 26.png", category: 'Weddings' },
  { src: "/image copy 27.png", category: 'Weddings' },
  { src: "/image copy 28.png", category: 'Weddings' },
  { src: "/image copy 29.png", category: 'Weddings' },
  { src: "/image copy 30.png", category: 'Weddings' },
  { src: "/image copy 31.png", category: 'Weddings' },
  { src: "/image copy 32.png", category: 'Weddings' },
  { src: "/image copy 33.png", category: 'Weddings' },
  { src: "/image copy 34.png", category: 'Weddings' },
  { src: "/image copy 35.png", category: 'Weddings' },
  { src: "/image copy 36.png", category: 'Weddings' },
  { src: "/image copy 37.png", category: 'Weddings' },
  { src: "/image copy 38.png", category: 'Weddings' },
  { src: "/image copy 39.png", category: 'Weddings' },
  { src: "/image copy 40.png", category: 'Weddings' },
  // Weddings
  { src: "https://res.cloudinary.com/duha1w6d3/image/upload/v1779031101/WhatsApp_Image_2026-05-16_at_10.03.54_PM_6_yy16di", category: 'Corporate' },
  { src: "https://res.cloudinary.com/duha1w6d3/image/upload/v1779031100/WhatsApp_Image_2026-05-16_at_10.03.54_PM_7_tig7ti", category: 'Corporate' },
  { src: "https://res.cloudinary.com/duha1w6d3/image/upload/v1779031100/WhatsApp_Image_2026-05-16_at_10.03.53_PM_9_kyvxmq", category: 'Corporate' },
  { src: "https://res.cloudinary.com/duha1w6d3/image/upload/v1779031100/WhatsApp_Image_2026-05-16_at_10.03.54_PM_4_zwlu2c", category: 'Corporate' },
  { src: "https://res.cloudinary.com/duha1w6d3/image/upload/v1779031099/WhatsApp_Image_2026-05-16_at_10.03.53_PM_ttaiaa", category: 'Corporate' },
  { src: "https://res.cloudinary.com/duha1w6d3/image/upload/v1779031099/WhatsApp_Image_2026-05-16_at_10.03.54_PM_1_bxf0q7", category: 'Corporate' },
  { src: "https://res.cloudinary.com/duha1w6d3/image/upload/v1779031098/WhatsApp_Image_2026-05-16_at_10.03.49_PM_4_gne1o2", category: 'Corporate' },
  { src: "https://res.cloudinary.com/duha1w6d3/image/upload/v1779031098/WhatsApp_Image_2026-05-16_at_10.03.54_PM_2_gqfqbk", category: 'Corporate' },
  { src: "https://res.cloudinary.com/duha1w6d3/image/upload/v1779031097/WhatsApp_Image_2026-05-16_at_10.03.53_PM_8_ohmtyl", category: 'Corporate' },
  { src: "https://res.cloudinary.com/duha1w6d3/image/upload/v1779031092/WhatsApp_Image_2026-05-16_at_10.03.45_PM_3_mzphhz", category: 'Corporate' },
  { src: "https://res.cloudinary.com/duha1w6d3/image/upload/v1779031091/WhatsApp_Image_2026-05-16_at_10.03.53_PM_1_f2hpco", category: 'Corporate' },
  { src: "https://res.cloudinary.com/duha1w6d3/image/upload/v1779031091/WhatsApp_Image_2026-05-16_at_10.03.49_PM_3_p98yly", category: 'Corporate' },
  { src: "https://res.cloudinary.com/duha1w6d3/image/upload/v1779031089/WhatsApp_Image_2026-05-16_at_10.03.45_PM_2_lbhhvn", category: 'Corporate' },
  { src: "https://res.cloudinary.com/duha1w6d3/image/upload/v1779031088/WhatsApp_Image_2026-05-16_at_10.03.52_PM_3_i5znvk", category: 'Corporate' },
  { src: "https://res.cloudinary.com/duha1w6d3/image/upload/v1779031088/WhatsApp_Image_2026-05-16_at_10.03.45_PM_1_cbqdql", category: 'Corporate' },
  // Birthdays & Milestones
  { src: "https://res.cloudinary.com/duha1w6d3/image/upload/v1779031088/WhatsApp_Image_2026-05-16_at_10.03.52_PM_2_dg5kvg", category: 'Birthdays & Milestones' },
  { src: "https://res.cloudinary.com/duha1w6d3/image/upload/v1779031088/y_giyx5k", category: 'Birthdays & Milestones' },
  { src: "https://res.cloudinary.com/duha1w6d3/image/upload/v1779031087/WhatsApp_Image_2026-05-16_at_10.03.48_PM_8_hglyfw", category: 'Birthdays & Milestones' },
  { src: "https://res.cloudinary.com/duha1w6d3/image/upload/v1779031087/WhatsApp_Image_2026-05-16_at_10.03.52_PM_nvzosx", category: 'Birthdays & Milestones' },
  { src: "https://res.cloudinary.com/duha1w6d3/image/upload/v1779031086/WhatsApp_Image_2026-05-16_at_10.03.48_PM_cixayd", category: 'Birthdays & Milestones' },
  { src: "https://res.cloudinary.com/duha1w6d3/image/upload/v1779031085/WhatsApp_Image_2026-05-16_at_10.03.48_PM_2_eiwihd", category: 'Birthdays & Milestones' },
  { src: "https://res.cloudinary.com/duha1w6d3/image/upload/v1779031085/WhatsApp_Image_2026-05-16_at_10.03.57_PM_6_isuyan", category: 'Birthdays & Milestones' },
  { src: "https://res.cloudinary.com/duha1w6d3/image/upload/v1779031085/WhatsApp_Image_2026-05-16_at_10.03.57_PM_gsq7mu", category: 'Birthdays & Milestones' },
  { src: "https://res.cloudinary.com/duha1w6d3/image/upload/v1779031084/WhatsApp_Image_2026-05-16_at_10.03.57_PM_5_qikxz7", category: 'Birthdays & Milestones' },
  { src: "https://res.cloudinary.com/duha1w6d3/image/upload/v1779031083/WhatsApp_Image_2026-05-16_at_10.03.44_PM_aoozvh", category: 'Birthdays & Milestones' },
  { src: "https://res.cloudinary.com/duha1w6d3/image/upload/v1779031083/e_h1s6lp", category: 'Birthdays & Milestones' },
  { src: "https://res.cloudinary.com/duha1w6d3/image/upload/v1779031083/w_kqrfx1", category: 'Birthdays & Milestones' },
  { src: "https://res.cloudinary.com/duha1w6d3/image/upload/v1779031083/WhatsApp_Image_2026-05-16_at_10.03.49_PM_2_b1mhfc", category: 'Birthdays & Milestones' },
  { src: "https://res.cloudinary.com/duha1w6d3/image/upload/v1779031083/r_uhswjb", category: 'Birthdays & Milestones' },
  { src: "https://res.cloudinary.com/duha1w6d3/image/upload/v1779031082/u_b5jb3p", category: 'Birthdays & Milestones' },
  // Corporate
  { src: "https://res.cloudinary.com/duha1w6d3/image/upload/v1779031082/WhatsApp_Image_2026-05-16_at_10.03.57_PM_3_cdycfn", category: 'Corporate' },
  { src: "https://res.cloudinary.com/duha1w6d3/image/upload/v1779031081/WhatsApp_Image_2026-05-16_at_10.03.57_PM_4_bkxigw", category: 'Corporate' },
  { src: "https://res.cloudinary.com/duha1w6d3/image/upload/v1779031019/WhatsApp_Image_2026-05-16_at_10.03.45_PM_4_ondvpg.jpg", category: 'Corporate' },
  { src: "https://res.cloudinary.com/duha1w6d3/image/upload/v1779031020/WhatsApp_Image_2026-05-16_at_10.03.55_PM_3_a5ktus.jpg", category: 'Corporate' },
  { src: "https://res.cloudinary.com/duha1w6d3/image/upload/v1779031033/WhatsApp_Image_2026-05-16_at_10.03.55_PM_6_udoc3b.jpg", category: 'Corporate' },
  { src: "https://res.cloudinary.com/duha1w6d3/image/upload/v1779031034/WhatsApp_Image_2026-05-16_at_10.03.55_PM_7_vbcciz.jpg", category: 'Corporate' },
  { src: "https://res.cloudinary.com/duha1w6d3/image/upload/v1779031022/o_nessus.jpg", category: 'Corporate' },
  { src: "https://res.cloudinary.com/duha1w6d3/image/upload/v1779031021/WhatsApp_Image_2026-05-16_at_10.03.55_PM_4_kfkcte.jpg", category: 'Corporate' },
  { src: "https://res.cloudinary.com/duha1w6d3/image/upload/v1779031047/WhatsApp_Image_2026-05-16_at_10.03.49_PM_p7rkay.jpg", category: 'Corporate' },
  { src: "https://res.cloudinary.com/duha1w6d3/image/upload/v1779031045/WhatsApp_Image_2026-05-16_at_10.03.49_PM_8_nef18q.jpg", category: 'Corporate' },
  { src: "https://res.cloudinary.com/duha1w6d3/image/upload/v1779031066/WhatsApp_Image_2026-05-16_at_10.03.48_PM_6_ucbvmq.jpg", category: 'Corporate' },
  { src: "https://res.cloudinary.com/duha1w6d3/image/upload/v1779031066/WhatsApp_Image_2026-05-16_at_10.03.55_PM_5_py7qpi.jpg", category: 'Corporate' },
  { src: "https://res.cloudinary.com/duha1w6d3/image/upload/v1779031054/WhatsApp_Image_2026-05-16_at_10.03.48_PM_5_ozck58.jpg", category: 'Corporate' },
  { src: "https://res.cloudinary.com/duha1w6d3/image/upload/v1779031068/WhatsApp_Image_2026-05-16_at_10.03.55_PM_h0tq3q.jpg", category: 'Corporate' },
  { src: "https://res.cloudinary.com/duha1w6d3/image/upload/v1779031069/WhatsApp_Image_2026-05-16_at_10.03.56_PM_1_yqr57m.jpg", category: 'Corporate' },
  { src: "https://res.cloudinary.com/duha1w6d3/image/upload/v1779031071/WhatsApp_Image_2026-05-16_at_10.03.53_PM_5_t5nkyo.jpg", category: 'Corporate' },
  { src: "https://res.cloudinary.com/duha1w6d3/image/upload/v1779031071/WhatsApp_Image_2026-05-16_at_10.03.53_PM_6_lb5skv.jpg", category: 'Corporate' },
  { src: "https://res.cloudinary.com/duha1w6d3/image/upload/v1779031071/WhatsApp_Image_2026-05-16_at_10.03.56_PM_3_h5weyg.jpg", category: 'Corporate' },
  { src: "https://res.cloudinary.com/duha1w6d3/image/upload/v1779031072/WhatsApp_Image_2026-05-16_at_10.03.48_PM_7_l6qmef.jpg", category: 'Corporate' },
  { src: "https://res.cloudinary.com/duha1w6d3/image/upload/v1779031073/WhatsApp_Image_2026-05-16_at_10.03.49_PM_7_eiprnf.jpg", category: 'Corporate' },
  { src: "https://res.cloudinary.com/duha1w6d3/image/upload/v1779031073/WhatsApp_Image_2026-05-16_at_10.03.53_PM_7_honcli.jpg", category: 'Corporate' },
  { src: "https://res.cloudinary.com/duha1w6d3/image/upload/v1779031075/WhatsApp_Image_2026-05-16_at_10.03.56_PM_5_egcgdj.jpg", category: 'Corporate' },
  { src: "https://res.cloudinary.com/duha1w6d3/image/upload/v1779031076/WhatsApp_Image_2026-05-16_at_10.03.56_PM_6_bignmz.jpg", category: 'Corporate' },
  { src: "https://res.cloudinary.com/duha1w6d3/image/upload/v1779031076/WhatsApp_Image_2026-05-16_at_10.03.56_PM_8_jljdnq.jpg", category: 'Corporate' },
  { src: "https://res.cloudinary.com/duha1w6d3/image/upload/v1779031076/WhatsApp_Image_2026-05-16_at_10.03.56_PM_7_a7bsoh.jpg", category: 'Corporate' },
  { src: "https://res.cloudinary.com/duha1w6d3/image/upload/v1779031078/WhatsApp_Image_2026-05-16_at_10.03.53_PM_2_j6hjdp.jpg", category: 'Corporate' },
  { src: "https://res.cloudinary.com/duha1w6d3/image/upload/v1779031078/q_lmif1i.jpg", category: 'Corporate' },
  { src: "https://res.cloudinary.com/duha1w6d3/image/upload/v1779031079/WhatsApp_Image_2026-05-16_at_10.03.53_PM_4_q5zgne.jpg", category: 'Corporate' },
  { src: "https://res.cloudinary.com/duha1w6d3/image/upload/v1779031079/WhatsApp_Image_2026-05-16_at_10.03.53_PM_3_ufdikf.jpg", category: 'Corporate' },
  { src: "https://res.cloudinary.com/duha1w6d3/image/upload/v1779031081/WhatsApp_Image_2026-05-16_at_10.03.49_PM_1_oqmkcl.jpg", category: 'Corporate' },
  { src: "https://res.cloudinary.com/duha1w6d3/image/upload/v1779031081/WhatsApp_Image_2026-05-16_at_10.03.57_PM_1_rsii3p.jpg", category: 'Corporate' },
  { src: "https://res.cloudinary.com/duha1w6d3/image/upload/v1779031083/WhatsApp_Image_2026-05-16_at_10.03.49_PM_2_b1mhfc.jpg", category: 'Corporate' },
  { src: "https://res.cloudinary.com/duha1w6d3/image/upload/v1779031083/WhatsApp_Image_2026-05-16_at_10.03.44_PM_aoozvh.jpg", category: 'Corporate' },
  { src: "https://res.cloudinary.com/duha1w6d3/image/upload/v1779031084/WhatsApp_Image_2026-05-16_at_10.03.57_PM_5_qikxz7.jpg", category: 'Corporate' },
];

